# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

inhibit_all_warnings!

target 'Book Store' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for Book Store
  pod 'AFNetworking'
  pod 'JSONModel'
  pod 'SDWebImage'
  pod 'SVProgressHUD'
  pod 'UIActivityIndicator-for-SDWebImage'

  target 'Book StoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Book StoreUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
